# Generated by Django 5.0 on 2024-01-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_brand',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
