# Generated by Django 5.0 on 2024-01-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_car_brand_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
