# Generated by Django 5.0 on 2024-01-17 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='cars/media/upload'),
        ),
    ]
